### ISSUE TITLE
Bring back length in GenResult?

### ISSUE THREAD

**Issue by Keruspe** [rust-bakery/cookie-factory#27]
I understand that

```
let buf = foo(buf)?;
let buf = bar(buf)?;
Ok(buf)
```

can feel smoother than

```
let (buf, len) = foo(buf)?;
let (buf, len) = bar(buf).map(|(buf, len2)| (buf, len + len2))?;
Ok((buf, len))
```

Though I still think this is an acceptable compromise:

```
let gen = foo.chain(&bar);
gen(buf)
```

One of the point that was brought up was the need to calculate the written length. In all the provided helpers, the write trait already gives us this data. Is there any concrete example of a case where this would be expansive?

Having to wrap everything in WriteCounter, and introducing hacks such as BackToTheBuffer, when used in real world applications, is really expansive on the other hand.

Take this simple integration test for example: https://github.com/sozu-proxy/amq-protocol/blob/b2db9c71bc617424cfe018ad9cd6c0f13273ec7e/types/tests/integration.rs
It uses BackToTheBuffer and WriteCounter recursively to write stuff (imagine a table of elements, which can themselves be tables, etc).

I had to add `#![recursion_limit="1024"]` for it to even start to compile (compiler suggested 128, then 256, etc..).
Once recursion limit has been set comes the type length, I did tenth of compiler cycles by now I think, and still haven't reached a value for which it actually finishes building. Current value is `#![type_length_limit="1630195223"]`

**Comment by Keruspe** [comment]
Unless someone has an idea to workaround this problem and has real arguments wrt the cost of adding the lenth to GenResult, I'm going to add it back.

**Comment by Keruspe** [comment]
Poke @sdroege as you were the one to drop it

**Comment by Keruspe** [comment]
Thinking back of the examples from above, there is even a way to be closer to the "length-less" approach by just using `.0` for the serializers we provide, and then just not using GenResult but a simple `Result<Foo, GenError>` in custom serializers:

```
let buf = foo(buf)?.0;
let buf = bar(buf)?.0;
Ok(buf)
```

**Comment by sdroege** [comment]
> introducing hacks such as BackToTheBuffer

I wouldn't call this a hack but it's a useful combinator to have regardless of everything else.

> Thinking back of the examples from above, there is even a way to be closer to the "length-less" approach by just using `.0` for the serializers we provide, and then just not using GenResult but a simple `Result<Foo, GenError>` in custom serializers:
> 
> ```
> let buf = foo(buf)?.0;
> let buf = bar(buf)?.0;
> Ok(buf)
> ```

You can't do this when writing combinators yourself. Inside your own combinators you would always have to ensure to pass through the length correctly everywhere and add it correctly together, which is a rather error-prone and manual job.

In every `SerializeFn` that is not just a combination of combinators (i.e. you have to write the closure yourself), you would have to keep track of the lengths correctly. I don't think that scales well either.

And you'd have to bring back hacks like the `GenResult` combinators and using the normal `Result` combinators would break the expected behaviour (as the length wouldn't be accumulated).

I think passing through the length as-is is not really the solution we're looking for here.

**Comment by sdroege** [comment]
Or to summarize: returning the length directly would make it impossible to use the `Result` combinators and you need *something* to add together the lengths. And don't ever accidentally use any of the `Result` combinators, or do a mistake in accumulating the lengths, or otherwise everything will fall apart.

**Comment by Keruspe** [comment]
Maybe a mix of the previous and the current approach with some tuple such as the WriteCounter would make sense?

```
let buf = (buf, 0);
let buf = foo(buf)?;
let buf = bar(buf)?;
Ok(buf)
```

**Comment by sdroege** [comment]
You mean to pass not a `Write` though the combinators but instead some `pub struct Blabla<W: Write>(W, usize)`, and have everything operate on that struct instead of `Write` (and have it proxy the `Write` API)?

That would work I guess, the only disadvantages would be
- We would always calculate the lengths but the performance impact can be ignored IMHO
- If you have a combinator that requires a specific `Write` impl, you still need the possibility to poke it out of the struct, do your stuff, put the updated value back and then also correctly update the `usize`

Seems acceptable to me. We could call this struct `WriteContext` maybe

**Comment by sdroege** [comment]
Doing a test implementation of that now btw
